export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";

export const GET_USER_TOKEN = "GET_USER_TOKEN";

export const AUTH_REGISTER_REQUEST = "AUTH_REGISTER_REQUEST";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAIL = "AUTH_REGISTER_FAIL";

export const AUTH_ACTIVATE_EMAIL_SUCCESS = "AUTH_ACTIVATE_EMAIL_SUCCESS";
export const AUTH_ACTIVATE_EMAIL_FAIL = "AUTH_ACTIVATE_EMAIL_FAIL";


export const AUTH_CLEAR_ERROR = "AUTH_CLEAR_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOGOUT_FAIL = "AUTH_LOGOUT_FAIL";

export const AUTH_GOOGLE_LOGIN_REQUEST = "AUTH_GOOGLE_LOGIN_REQUEST";
export const AUTH_GOOGLE_LOGIN_SUCCESS = "AUTH_GOOGLE_LOGIN_SUCCESS";
export const AUTH_GOOGLE_LOGIN_FAIL = "AUTH_GOOGLE_LOGIN_FAIL";