export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

// export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
// export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
// export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
// export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

