const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';
const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";
const DOWNLOAD_STARTED = "DOWNLOAD_STARTED";
const DOWNLOAD_COMPLETE = "DOWNLOAD_COMPLETE";
const DOWNLOAD_ERROR = "DOWNLOAD_ERROR";

export {
  PRODUCT_LIST_REQUEST,
  PRODUCT_LIST_FAIL,
  PRODUCT_LIST_SUCCESS,
  PRODUCT_DETAILS_REQUEST,
  PRODUCT_DETAILS_SUCCESS,
  PRODUCT_DETAILS_FAIL,
  DOWNLOAD_ERROR,
  DOWNLOAD_COMPLETE,
  DOWNLOAD_STARTED,
};