const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export {
  PRODUCT_LIST_REQUEST,
  PRODUCT_SUCCESS,
  PRODUCT_LIST_FAIL
}